### ISSUE TITLE
Create MindMap of the website

### ISSUE THREAD

**Issue by admin-estiem-lg-seville** [ESTIEM-LG-Seville/ELGS-vue#4]
The idea is to do a map of how what we will put in the website. How the structure will be...? Will we have any sort of Menu?

### Aditional Comments

- Podemos subirlo a la unidad compartida del PRC ó directamente adjuntar el archivo al issue

**Comment by David-ByHunter** [comment]
@luccancal He pensado en este 
[ESTIEM LG SEVILLE WEB PAGE.pdf](https://github.com/ESTIEM-LG-Seville/ELGS-vue/files/10860295/ESTIEM.LG.SEVILLE.WEB.PAGE.pdf)
mapa conceptual de la empresa. Dame feedback cuando Puedas
